services:
  - type: web
    name: lms-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: JWT_COOKIE_EXPIRE
        value: 7
      - key: CLIENT_URL
        value: https://your-netlify-app.netlify.app
      - key: CORS_ORIGIN
        value: https://your-netlify-app.netlify.app
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
